# Build settings

port: 4000
markdown:  kramdown
permalink: /:title
plugins:   [jekyll-sitemap, jekyll-feed,  jekyll-seo-tag]

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)

title:		   "Tundra Toucan"
description: "Tundra Toucan's Logos and Illustrations"
author:      "Gerrit Rijken"
